//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: c2g.proto
namespace C2G
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VersionInfo")]
  public partial class VersionInfo : global::ProtoBuf.IExtensible
  {
    public VersionInfo() {}
    

    private ulong _id = (ulong)391770;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)391770)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _version = @"0.1.2";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"0.1.2")]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterAccount")]
  public partial class RegisterAccount : global::ProtoBuf.IExtensible
  {
    public RegisterAccount() {}
    

    private ulong _id = (ulong)1376019;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)1376019)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _k_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string k_id
    {
      get { return _k_id; }
      set { _k_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnregisterAccount")]
  public partial class UnregisterAccount : global::ProtoBuf.IExtensible
  {
    public UnregisterAccount() {}
    

    private ulong _id = (ulong)2358542;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)2358542)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Login")]
  public partial class Login : global::ProtoBuf.IExtensible
  {
    public Login() {}
    

    private ulong _id = (ulong)12322730;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)12322730)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _k_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string k_id
    {
      get { return _k_id; }
      set { _k_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Logout")]
  public partial class Logout : global::ProtoBuf.IExtensible
  {
    public Logout() {}
    

    private ulong _id = (ulong)389941;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)389941)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckInCharge")]
  public partial class CheckInCharge : global::ProtoBuf.IExtensible
  {
    public CheckInCharge() {}
    

    private ulong _id = (ulong)390853;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)390853)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectCharacter")]
  public partial class SelectCharacter : global::ProtoBuf.IExtensible
  {
    public SelectCharacter() {}
    

    private ulong _id = (ulong)1179073;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)1179073)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _selected_character;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"selected_character", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int selected_character
    {
      get { return _selected_character; }
      set { _selected_character = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartGame")]
  public partial class StartGame : global::ProtoBuf.IExtensible
  {
    public StartGame() {}
    

    private ulong _id = (ulong)391039;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)391039)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EndGame")]
  public partial class EndGame : global::ProtoBuf.IExtensible
  {
    public EndGame() {}
    

    private ulong _id = (ulong)6420788;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)6420788)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _dist;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"dist", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dist
    {
      get { return _dist; }
      set { _dist = value; }
    }
    private int _enemy_kill;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"enemy_kill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int enemy_kill
    {
      get { return _enemy_kill; }
      set { _enemy_kill = value; }
    }
    private int _play_time;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"play_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int play_time
    {
      get { return _play_time; }
      set { _play_time = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _mileage;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"mileage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mileage
    {
      get { return _mileage; }
      set { _mileage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadRankInfo")]
  public partial class LoadRankInfo : global::ProtoBuf.IExtensible
  {
    public LoadRankInfo() {}
    

    private ulong _id = (ulong)7468663;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)7468663)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyItem")]
  public partial class BuyItem : global::ProtoBuf.IExtensible
  {
    public BuyItem() {}
    

    private ulong _id = (ulong)5436810;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)5436810)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _item;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item
    {
      get { return _item; }
      set { _item = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Limit")]
    public enum Limit
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MIN", Value=1)]
      MIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX", Value=6)]
      MAX = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyOrUpgradeCharacter")]
  public partial class BuyOrUpgradeCharacter : global::ProtoBuf.IExtensible
  {
    public BuyOrUpgradeCharacter() {}
    

    private ulong _id = (ulong)7467298;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)7467298)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _character;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"character", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int character
    {
      get { return _character; }
      set { _character = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendEnergy")]
  public partial class SendEnergy : global::ProtoBuf.IExtensible
  {
    public SendEnergy() {}
    

    private ulong _id = (ulong)2489592;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)2489592)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _receiver_k_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"receiver_k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string receiver_k_id
    {
      get { return _receiver_k_id; }
      set { _receiver_k_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcceptEnergy")]
  public partial class AcceptEnergy : global::ProtoBuf.IExtensible
  {
    public AcceptEnergy() {}
    

    private ulong _id = (ulong)3470937;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)3470937)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _sender_k_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sender_k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sender_k_id
    {
      get { return _sender_k_id; }
      set { _sender_k_id = value; }
    }
    private long _sended_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sended_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sended_time
    {
      get { return _sended_time; }
      set { _sended_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestBaton")]
  public partial class RequestBaton : global::ProtoBuf.IExtensible
  {
    public RequestBaton() {}
    

    private ulong _id = (ulong)3472750;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)3472750)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _receiver_k_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"receiver_k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string receiver_k_id
    {
      get { return _receiver_k_id; }
      set { _receiver_k_id = value; }
    }
    private string _map;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"map", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string map
    {
      get { return _map; }
      set { _map = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcceptBaton")]
  public partial class AcceptBaton : global::ProtoBuf.IExtensible
  {
    public AcceptBaton() {}
    

    private ulong _id = (ulong)3534913;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)3534913)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _sender_k_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sender_k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sender_k_id
    {
      get { return _sender_k_id; }
      set { _sender_k_id = value; }
    }
    private long _sended_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sended_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sended_time
    {
      get { return _sended_time; }
      set { _sended_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EndBaton")]
  public partial class EndBaton : global::ProtoBuf.IExtensible
  {
    public EndBaton() {}
    

    private ulong _id = (ulong)1505624;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)1505624)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _sender_k_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sender_k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sender_k_id
    {
      get { return _sender_k_id; }
      set { _sender_k_id = value; }
    }
    private long _sended_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sended_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sended_time
    {
      get { return _sended_time; }
      set { _sended_time = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _dist;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"dist", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dist
    {
      get { return _dist; }
      set { _dist = value; }
    }
    private int _enemy_kill;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"enemy_kill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int enemy_kill
    {
      get { return _enemy_kill; }
      set { _enemy_kill = value; }
    }
    private int _play_time;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"play_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int play_time
    {
      get { return _play_time; }
      set { _play_time = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcceptBatonResult")]
  public partial class AcceptBatonResult : global::ProtoBuf.IExtensible
  {
    public AcceptBatonResult() {}
    

    private ulong _id = (ulong)1569529;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)1569529)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _sender_k_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sender_k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sender_k_id
    {
      get { return _sender_k_id; }
      set { _sender_k_id = value; }
    }
    private long _sended_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sended_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sended_time
    {
      get { return _sended_time; }
      set { _sended_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InviteFriend")]
  public partial class InviteFriend : global::ProtoBuf.IExtensible
  {
    public InviteFriend() {}
    

    private ulong _id = (ulong)7533273;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)7533273)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _friend_k_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"friend_k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string friend_k_id
    {
      get { return _friend_k_id; }
      set { _friend_k_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadReward")]
  public partial class LoadReward : global::ProtoBuf.IExtensible
  {
    public LoadReward() {}
    

    private ulong _id = (ulong)2555567;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)2555567)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private C2G.LoadReward.Reward _reward;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public C2G.LoadReward.Reward reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Reward")]
    public enum Reward
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVITE_10_REWARD", Value=1)]
      INVITE_10_REWARD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVITE_15_REWARD", Value=2)]
      INVITE_15_REWARD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVITE_30_REWARD", Value=3)]
      INVITE_30_REWARD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX", Value=4)]
      MAX = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyCostume")]
  public partial class BuyCostume : global::ProtoBuf.IExtensible
  {
    public BuyCostume() {}
    

    private ulong _id = (ulong)7535719;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)7535719)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _costume_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"costume_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int costume_id
    {
      get { return _costume_id; }
      set { _costume_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WearCostume")]
  public partial class WearCostume : global::ProtoBuf.IExtensible
  {
    public WearCostume() {}
    

    private ulong _id = (ulong)7534631;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)7534631)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _costume_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"costume_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int costume_id
    {
      get { return _costume_id; }
      set { _costume_id = value; }
    }
    private int _character_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"character_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int character_id
    {
      get { return _character_id; }
      set { _character_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DrawFirst")]
  public partial class DrawFirst : global::ProtoBuf.IExtensible
  {
    public DrawFirst() {}
    

    private ulong _id = (ulong)1570213;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)1570213)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DrawSecond")]
  public partial class DrawSecond : global::ProtoBuf.IExtensible
  {
    public DrawSecond() {}
    

    private ulong _id = (ulong)5566939;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)5566939)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bool _draw;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"draw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool draw
    {
      get { return _draw; }
      set { _draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipGhost")]
  public partial class EquipGhost : global::ProtoBuf.IExtensible
  {
    public EquipGhost() {}
    

    private ulong _id = (ulong)588139;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)588139)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _ghost_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ghost_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ghost_id
    {
      get { return _ghost_id; }
      set { _ghost_id = value; }
    }
    private int _house_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"house_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int house_id
    {
      get { return _house_id; }
      set { _house_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnequipGhost")]
  public partial class UnequipGhost : global::ProtoBuf.IExtensible
  {
    public UnequipGhost() {}
    

    private ulong _id = (ulong)586959;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)586959)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _house_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"house_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int house_id
    {
      get { return _house_id; }
      set { _house_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PurchaseHouse")]
  public partial class PurchaseHouse : global::ProtoBuf.IExtensible
  {
    public PurchaseHouse() {}
    

    private ulong _id = (ulong)15859063;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)15859063)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _house_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"house_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int house_id
    {
      get { return _house_id; }
      set { _house_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestEvolution")]
  public partial class RequestEvolution : global::ProtoBuf.IExtensible
  {
    public RequestEvolution() {}
    

    private ulong _id = (ulong)1375509;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)1375509)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _receiver_k_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"receiver_k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string receiver_k_id
    {
      get { return _receiver_k_id; }
      set { _receiver_k_id = value; }
    }
    private int _character_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"character_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int character_id
    {
      get { return _character_id; }
      set { _character_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcceptEvolution")]
  public partial class AcceptEvolution : global::ProtoBuf.IExtensible
  {
    public AcceptEvolution() {}
    

    private ulong _id = (ulong)4649758;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)4649758)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _sender_k_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sender_k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sender_k_id
    {
      get { return _sender_k_id; }
      set { _sender_k_id = value; }
    }
    private int _character_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"character_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int character_id
    {
      get { return _character_id; }
      set { _character_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadEvolutionProgress")]
  public partial class LoadEvolutionProgress : global::ProtoBuf.IExtensible
  {
    public LoadEvolutionProgress() {}
    

    private ulong _id = (ulong)1635192;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)1635192)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadPostbox")]
  public partial class LoadPostbox : global::ProtoBuf.IExtensible
  {
    public LoadPostbox() {}
    

    private ulong _id = (ulong)1637005;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)1637005)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}