//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: g2c.proto
namespace G2C
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SystemMessage")]
  public partial class SystemMessage : global::ProtoBuf.IExtensible
  {
    public SystemMessage() {}
    

    private ulong _id = (ulong)131068445;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private G2C.SystemMessage.Result _res;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public G2C.SystemMessage.Result res
    {
      get { return _res; }
      set { _res = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Result")]
    public enum Result
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRUE", Value=1)]
      TRUE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_ACCOUNT", Value=2)]
      INVALID_ACCOUNT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNDEFINED_FIELD", Value=3)]
      UNDEFINED_FIELD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXISTED_ACCOUNT", Value=4)]
      EXISTED_ACCOUNT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLOCKED_ACCOUNT", Value=5)]
      BLOCKED_ACCOUNT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DUPLICATED_LOGIN", Value=6)]
      DUPLICATED_LOGIN = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_CHARACTER", Value=7)]
      INVALID_CHARACTER = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_ITEM", Value=9)]
      INVALID_ITEM = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_ENERGY", Value=10)]
      NOT_ENOUGH_ENERGY = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_COIN", Value=11)]
      NOT_ENOUGH_COIN = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_MONEY", Value=12)]
      NOT_ENOUGH_MONEY = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_MATCH_WITH_DB", Value=13)]
      NO_MATCH_WITH_DB = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_BATON", Value=14)]
      INVALID_BATON = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_BATON_RESULT", Value=15)]
      INVALID_BATON_RESULT = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_ENERGY", Value=16)]
      INVALID_ENERGY = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FULLY_UPGRADED", Value=17)]
      FULLY_UPGRADED = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILED_DB_UPDATE", Value=18)]
      FAILED_DB_UPDATE = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_SESSION", Value=19)]
      INVALID_SESSION = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_COSTUME_CATEGORY", Value=20)]
      INVALID_COSTUME_CATEGORY = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_COSTUME_ID", Value=21)]
      INVALID_COSTUME_ID = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PURCHASE_FIRST", Value=22)]
      PURCHASE_FIRST = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_UPGRADE", Value=23)]
      INVALID_UPGRADE = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_DRAW", Value=24)]
      NOT_ENOUGH_DRAW = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_GHOST", Value=25)]
      INVALID_GHOST = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAN_NOT_PURCHASE", Value=26)]
      CAN_NOT_PURCHASE = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_ROOM", Value=27)]
      INVALID_ROOM = 27
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VersionInfoReply")]
  public partial class VersionInfoReply : global::ProtoBuf.IExtensible
  {
    public VersionInfoReply() {}
    

    private ulong _id = (ulong)1089076202;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _version;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterAccountReply")]
  public partial class RegisterAccountReply : global::ProtoBuf.IExtensible
  {
    public RegisterAccountReply() {}
    

    private ulong _id = (ulong)3142601;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnregisterAccountReply")]
  public partial class UnregisterAccountReply : global::ProtoBuf.IExtensible
  {
    public UnregisterAccountReply() {}
    

    private ulong _id = (ulong)14416633;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectCharacterReply")]
  public partial class SelectCharacterReply : global::ProtoBuf.IExtensible
  {
    public SelectCharacterReply() {}
    

    private ulong _id = (ulong)45151918;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartGameReply")]
  public partial class StartGameReply : global::ProtoBuf.IExtensible
  {
    public StartGameReply() {}
    

    private ulong _id = (ulong)278724898;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _energy;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int energy
    {
      get { return _energy; }
      set { _energy = value; }
    }
    private long _last_charged_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"last_charged_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long last_charged_time
    {
      get { return _last_charged_time; }
      set { _last_charged_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccountInfo")]
  public partial class AccountInfo : global::ProtoBuf.IExtensible
  {
    public AccountInfo() {}
    

    private ulong _id = (ulong)76741253;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _money;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _energy;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int energy
    {
      get { return _energy; }
      set { _energy = value; }
    }
    private long _last_charged_time;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"last_charged_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long last_charged_time
    {
      get { return _last_charged_time; }
      set { _last_charged_time = value; }
    }
    private int _selected_character;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"selected_character", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int selected_character
    {
      get { return _selected_character; }
      set { _selected_character = value; }
    }
    private int _score_factor;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"score_factor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score_factor
    {
      get { return _score_factor; }
      set { _score_factor = value; }
    }
    private int _time_factor;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"time_factor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time_factor
    {
      get { return _time_factor; }
      set { _time_factor = value; }
    }
    private int _cooldown_factor;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"cooldown_factor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cooldown_factor
    {
      get { return _cooldown_factor; }
      set { _cooldown_factor = value; }
    }
    private int _shield;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"shield", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shield
    {
      get { return _shield; }
      set { _shield = value; }
    }
    private int _item_last;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"item_last", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item_last
    {
      get { return _item_last; }
      set { _item_last = value; }
    }
    private int _ghostify;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"ghostify", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ghostify
    {
      get { return _ghostify; }
      set { _ghostify = value; }
    }
    private int _weapon_reinforce;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"weapon_reinforce", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int weapon_reinforce
    {
      get { return _weapon_reinforce; }
      set { _weapon_reinforce = value; }
    }
    private int _exp_boost;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"exp_boost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp_boost
    {
      get { return _exp_boost; }
      set { _exp_boost = value; }
    }
    private int _max_attack;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"max_attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int max_attack
    {
      get { return _max_attack; }
      set { _max_attack = value; }
    }
    private int _bonus_heart;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"bonus_heart", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bonus_heart
    {
      get { return _bonus_heart; }
      set { _bonus_heart = value; }
    }
    private int _drop_up;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"drop_up", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int drop_up
    {
      get { return _drop_up; }
      set { _drop_up = value; }
    }
    private int _magnet;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"magnet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int magnet
    {
      get { return _magnet; }
      set { _magnet = value; }
    }
    private int _bonus_score;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"bonus_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bonus_score
    {
      get { return _bonus_score; }
      set { _bonus_score = value; }
    }
    private int _mileage;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"mileage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mileage
    {
      get { return _mileage; }
      set { _mileage = value; }
    }
    private int _draw;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int draw
    {
      get { return _draw; }
      set { _draw = value; }
    }
    private readonly global::System.Collections.Generic.List<G2C.AccountInfo.CharacterInfo> _characters = new global::System.Collections.Generic.List<G2C.AccountInfo.CharacterInfo>();
    [global::ProtoBuf.ProtoMember(22, Name=@"characters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<G2C.AccountInfo.CharacterInfo> characters
    {
      get { return _characters; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterInfo")]
  public partial class CharacterInfo : global::ProtoBuf.IExtensible
  {
    public CharacterInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _exp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogoutReply")]
  public partial class LogoutReply : global::ProtoBuf.IExtensible
  {
    public LogoutReply() {}
    

    private ulong _id = (ulong)1481109953;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChargeInfo")]
  public partial class ChargeInfo : global::ProtoBuf.IExtensible
  {
    public ChargeInfo() {}
    

    private ulong _id = (ulong)149157351;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _energy;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int energy
    {
      get { return _energy; }
      set { _energy = value; }
    }
    private long _last_charged_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"last_charged_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long last_charged_time
    {
      get { return _last_charged_time; }
      set { _last_charged_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankInfo")]
  public partial class RankInfo : global::ProtoBuf.IExtensible
  {
    public RankInfo() {}
    

    private ulong _id = (ulong)9108294;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private long _overall_ranking;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"overall_ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long overall_ranking
    {
      get { return _overall_ranking; }
      set { _overall_ranking = value; }
    }
    private readonly global::System.Collections.Generic.List<G2C.RankInfo.FriendRankInfo> _ranking_list = new global::System.Collections.Generic.List<G2C.RankInfo.FriendRankInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ranking_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<G2C.RankInfo.FriendRankInfo> ranking_list
    {
      get { return _ranking_list; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendRankInfo")]
  public partial class FriendRankInfo : global::ProtoBuf.IExtensible
  {
    public FriendRankInfo() {}
    
    private string _k_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string k_id
    {
      get { return _k_id; }
      set { _k_id = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private bool _energy_sended;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"energy_sended", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool energy_sended
    {
      get { return _energy_sended; }
      set { _energy_sended = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostedEnergy")]
  public partial class PostedEnergy : global::ProtoBuf.IExtensible
  {
    public PostedEnergy() {}
    

    private ulong _id = (ulong)130590;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<G2C.PostedEnergy.Energy> _energy = new global::System.Collections.Generic.List<G2C.PostedEnergy.Energy>();
    [global::ProtoBuf.ProtoMember(2, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<G2C.PostedEnergy.Energy> energy
    {
      get { return _energy; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Energy")]
  public partial class Energy : global::ProtoBuf.IExtensible
  {
    public Energy() {}
    
    private string _sender_k_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sender_k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sender_k_id
    {
      get { return _sender_k_id; }
      set { _sender_k_id = value; }
    }
    private long _sended_time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sended_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sended_time
    {
      get { return _sended_time; }
      set { _sended_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostedBaton")]
  public partial class PostedBaton : global::ProtoBuf.IExtensible
  {
    public PostedBaton() {}
    

    private ulong _id = (ulong)4127219;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<G2C.PostedBaton.Baton> _baton = new global::System.Collections.Generic.List<G2C.PostedBaton.Baton>();
    [global::ProtoBuf.ProtoMember(2, Name=@"baton", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<G2C.PostedBaton.Baton> baton
    {
      get { return _baton; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Baton")]
  public partial class Baton : global::ProtoBuf.IExtensible
  {
    public Baton() {}
    
    private string _sender_k_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sender_k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sender_k_id
    {
      get { return _sender_k_id; }
      set { _sender_k_id = value; }
    }
    private string _map_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"map_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string map_name
    {
      get { return _map_name; }
      set { _map_name = value; }
    }
    private int _last_score;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"last_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int last_score
    {
      get { return _last_score; }
      set { _last_score = value; }
    }
    private long _sended_time;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sended_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sended_time
    {
      get { return _sended_time; }
      set { _sended_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostedBatonResult")]
  public partial class PostedBatonResult : global::ProtoBuf.IExtensible
  {
    public PostedBatonResult() {}
    

    private ulong _id = (ulong)4191570;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<G2C.PostedBatonResult.BatonResult> _baton_result = new global::System.Collections.Generic.List<G2C.PostedBatonResult.BatonResult>();
    [global::ProtoBuf.ProtoMember(2, Name=@"baton_result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<G2C.PostedBatonResult.BatonResult> baton_result
    {
      get { return _baton_result; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BatonResult")]
  public partial class BatonResult : global::ProtoBuf.IExtensible
  {
    public BatonResult() {}
    
    private string _sender_k_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sender_k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sender_k_id
    {
      get { return _sender_k_id; }
      set { _sender_k_id = value; }
    }
    private int _acquisition_score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"acquisition_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int acquisition_score
    {
      get { return _acquisition_score; }
      set { _acquisition_score = value; }
    }
    private long _sended_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sended_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sended_time
    {
      get { return _sended_time; }
      set { _sended_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameResult")]
  public partial class GameResult : global::ProtoBuf.IExtensible
  {
    public GameResult() {}
    

    private ulong _id = (ulong)194297;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _bonus_score;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"bonus_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bonus_score
    {
      get { return _bonus_score; }
      set { _bonus_score = value; }
    }
    private int _total_score;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"total_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int total_score
    {
      get { return _total_score; }
      set { _total_score = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _exp;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _total_coin;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"total_coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int total_coin
    {
      get { return _total_coin; }
      set { _total_coin = value; }
    }
    private int _mileage;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"mileage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mileage
    {
      get { return _mileage; }
      set { _mileage = value; }
    }
    private int _draw;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int draw
    {
      get { return _draw; }
      set { _draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyItemReply")]
  public partial class BuyItemReply : global::ProtoBuf.IExtensible
  {
    public BuyItemReply() {}
    

    private ulong _id = (ulong)4191111;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _item;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item
    {
      get { return _item; }
      set { _item = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyOrUpgradeCharacterReply")]
  public partial class BuyOrUpgradeCharacterReply : global::ProtoBuf.IExtensible
  {
    public BuyOrUpgradeCharacterReply() {}
    

    private ulong _id = (ulong)6160160;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _character;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"character", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int character
    {
      get { return _character; }
      set { _character = value; }
    }
    private int _lv;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _money;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _mileage;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"mileage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mileage
    {
      get { return _mileage; }
      set { _mileage = value; }
    }
    private int _draw;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int draw
    {
      get { return _draw; }
      set { _draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendEnergyReply")]
  public partial class SendEnergyReply : global::ProtoBuf.IExtensible
  {
    public SendEnergyReply() {}
    

    private ulong _id = (ulong)5176176;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _mileage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mileage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mileage
    {
      get { return _mileage; }
      set { _mileage = value; }
    }
    private int _draw;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int draw
    {
      get { return _draw; }
      set { _draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestBatonReply")]
  public partial class RequestBatonReply : global::ProtoBuf.IExtensible
  {
    public RequestBatonReply() {}
    

    private ulong _id = (ulong)1241620;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcceptEnergyReply")]
  public partial class AcceptEnergyReply : global::ProtoBuf.IExtensible
  {
    public AcceptEnergyReply() {}
    

    private ulong _id = (ulong)8190199;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _energy;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int energy
    {
      get { return _energy; }
      set { _energy = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcceptBatonReply")]
  public partial class AcceptBatonReply : global::ProtoBuf.IExtensible
  {
    public AcceptBatonReply() {}
    

    private ulong _id = (ulong)6222682;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BatonResult")]
  public partial class BatonResult : global::ProtoBuf.IExtensible
  {
    public BatonResult() {}
    

    private ulong _id = (ulong)3274653;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _total_coin;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"total_coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int total_coin
    {
      get { return _total_coin; }
      set { _total_coin = value; }
    }
    private bool _update;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"update", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool update
    {
      get { return _update; }
      set { _update = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcceptBatonResultReply")]
  public partial class AcceptBatonResultReply : global::ProtoBuf.IExtensible
  {
    public AcceptBatonResultReply() {}
    

    private ulong _id = (ulong)4257084;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private G2C.AcceptBatonResultReply.Update _update;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"update", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public G2C.AcceptBatonResultReply.Update update
    {
      get { return _update; }
      set { _update = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Update")]
    public enum Update
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=2)]
      FAIL = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpgradeFactorReply")]
  public partial class UpgradeFactorReply : global::ProtoBuf.IExtensible
  {
    public UpgradeFactorReply() {}
    

    private ulong _id = (ulong)2291670;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _mileage;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mileage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mileage
    {
      get { return _mileage; }
      set { _mileage = value; }
    }
    private int _draw;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int draw
    {
      get { return _draw; }
      set { _draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InviteFriendReply")]
  public partial class InviteFriendReply : global::ProtoBuf.IExtensible
  {
    public InviteFriendReply() {}
    

    private ulong _id = (ulong)5240240;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _invite_count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"invite_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int invite_count
    {
      get { return _invite_count; }
      set { _invite_count = value; }
    }
    private int _mileage;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mileage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mileage
    {
      get { return _mileage; }
      set { _mileage = value; }
    }
    private int _draw;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int draw
    {
      get { return _draw; }
      set { _draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadRewardReply")]
  public partial class LoadRewardReply : global::ProtoBuf.IExtensible
  {
    public LoadRewardReply() {}
    

    private ulong _id = (ulong)3273641;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private G2C.LoadRewardReply.Reward _reward;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public G2C.LoadRewardReply.Reward reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Reward")]
    public enum Reward
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVITE_10_REWARD", Value=1)]
      INVITE_10_REWARD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVITE_15_REWARD", Value=2)]
      INVITE_15_REWARD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVITE_30_REWARD", Value=3)]
      INVITE_30_REWARD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX", Value=4)]
      MAX = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyCostumeReply")]
  public partial class BuyCostumeReply : global::ProtoBuf.IExtensible
  {
    public BuyCostumeReply() {}
    

    private ulong _id = (ulong)325704;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _costume_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"costume_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int costume_id
    {
      get { return _costume_id; }
      set { _costume_id = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _money;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _mileage;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mileage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mileage
    {
      get { return _mileage; }
      set { _mileage = value; }
    }
    private int _draw;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int draw
    {
      get { return _draw; }
      set { _draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WearCostumeReply")]
  public partial class WearCostumeReply : global::ProtoBuf.IExtensible
  {
    public WearCostumeReply() {}
    

    private ulong _id = (ulong)6290750;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _costume_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"costume_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int costume_id
    {
      get { return _costume_id; }
      set { _costume_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DrawFirstReply")]
  public partial class DrawFirstReply : global::ProtoBuf.IExtensible
  {
    public DrawFirstReply() {}
    

    private ulong _id = (ulong)9305604;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private G2C.DrawFirstReply.Draw _pick;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public G2C.DrawFirstReply.Draw pick
    {
      get { return _pick; }
      set { _pick = value; }
    }
    private readonly global::System.Collections.Generic.List<G2C.DrawFirstReply.Draw> _draw_list = new global::System.Collections.Generic.List<G2C.DrawFirstReply.Draw>();
    [global::ProtoBuf.ProtoMember(3, Name=@"draw_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<G2C.DrawFirstReply.Draw> draw_list
    {
      get { return _draw_list; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Draw")]
  public partial class Draw : global::ProtoBuf.IExtensible
  {
    public Draw() {}
    
    private bool _is_ghost;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"is_ghost", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_ghost
    {
      get { return _is_ghost; }
      set { _is_ghost = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DrawSecondReply")]
  public partial class DrawSecondReply : global::ProtoBuf.IExtensible
  {
    public DrawSecondReply() {}
    

    private ulong _id = (ulong)1178264;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private G2C.DrawSecondReply.Draw _pick;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public G2C.DrawSecondReply.Draw pick
    {
      get { return _pick; }
      set { _pick = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Draw")]
  public partial class Draw : global::ProtoBuf.IExtensible
  {
    public Draw() {}
    
    private bool _is_ghost;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"is_ghost", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_ghost
    {
      get { return _is_ghost; }
      set { _is_ghost = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipGhostReply")]
  public partial class EquipGhostReply : global::ProtoBuf.IExtensible
  {
    public EquipGhostReply() {}
    

    private ulong _id = (ulong)2356551;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _room_number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_number
    {
      get { return _room_number; }
      set { _room_number = value; }
    }
    private int _ghost_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ghost_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ghost_id
    {
      get { return _ghost_id; }
      set { _ghost_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnequipGhostReply")]
  public partial class UnequipGhostReply : global::ProtoBuf.IExtensible
  {
    public UnequipGhostReply() {}
    

    private ulong _id = (ulong)8322598;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _room_number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_number
    {
      get { return _room_number; }
      set { _room_number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PurchaseRoomReply")]
  public partial class PurchaseRoomReply : global::ProtoBuf.IExtensible
  {
    public PurchaseRoomReply() {}
    

    private ulong _id = (ulong)324416;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _room_number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_number
    {
      get { return _room_number; }
      set { _room_number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  

}