//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: g2c.proto
namespace G2C
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SystemMessage")]
  public partial class SystemMessage : global::ProtoBuf.IExtensible
  {
    public SystemMessage() {}
    

    private ulong _id = (ulong)131068445;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)131068445)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private G2C.SystemMessage.Result _res;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public G2C.SystemMessage.Result res
    {
      get { return _res; }
      set { _res = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Result")]
    public enum Result
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_ACCOUNT", Value=1)]
      INVALID_ACCOUNT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXISTING_ACCOUNT", Value=2)]
      EXISTING_ACCOUNT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLOCKED_ACCOUNT", Value=3)]
      BLOCKED_ACCOUNT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNDEFINED_FIELD", Value=20)]
      UNDEFINED_FIELD = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_ENERGY", Value=40)]
      NOT_ENOUGH_ENERGY = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_CASH", Value=41)]
      NOT_ENOUGH_CASH = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_COIN", Value=42)]
      NOT_ENOUGH_COIN = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_DRAW", Value=43)]
      NOT_ENOUGH_DRAW = 43,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILED_DB_UPDATE", Value=60)]
      FAILED_DB_UPDATE = 60,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FULLY_UPGRADED", Value=80)]
      FULLY_UPGRADED = 80,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_HAVING", Value=100)]
      NOT_HAVING = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALREADY_HAVING", Value=101)]
      ALREADY_HAVING = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_BATON", Value=120)]
      INVALID_BATON = 120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_BATON_RESULT", Value=121)]
      INVALID_BATON_RESULT = 121,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_CHARACTER", Value=122)]
      INVALID_CHARACTER = 122,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_ITEM", Value=123)]
      INVALID_ITEM = 123,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_SESSION", Value=124)]
      INVALID_SESSION = 124,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_COSTUME_ID", Value=125)]
      INVALID_COSTUME_ID = 125,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_GHOST", Value=126)]
      INVALID_GHOST = 126,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_HOUSE_ID", Value=127)]
      INVALID_HOUSE_ID = 127,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_EVOLUTION", Value=128)]
      INVALID_EVOLUTION = 128,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WRONG_APPROACH", Value=140)]
      WRONG_APPROACH = 140
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VersionInfoReply")]
  public partial class VersionInfoReply : global::ProtoBuf.IExtensible
  {
    public VersionInfoReply() {}
    

    private ulong _id = (ulong)1089076202;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)1089076202)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _version = @"0.1.3";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"0.1.3")]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterAccountReply")]
  public partial class RegisterAccountReply : global::ProtoBuf.IExtensible
  {
    public RegisterAccountReply() {}
    

    private ulong _id = (ulong)3142601;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)3142601)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnregisterAccountReply")]
  public partial class UnregisterAccountReply : global::ProtoBuf.IExtensible
  {
    public UnregisterAccountReply() {}
    

    private ulong _id = (ulong)14416633;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)14416633)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectCharacterReply")]
  public partial class SelectCharacterReply : global::ProtoBuf.IExtensible
  {
    public SelectCharacterReply() {}
    

    private ulong _id = (ulong)45151918;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)45151918)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartGameReply")]
  public partial class StartGameReply : global::ProtoBuf.IExtensible
  {
    public StartGameReply() {}
    

    private ulong _id = (ulong)278724898;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)278724898)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _energy;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int energy
    {
      get { return _energy; }
      set { _energy = value; }
    }
    private long _last_charged_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"last_charged_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long last_charged_time
    {
      get { return _last_charged_time; }
      set { _last_charged_time = value; }
    }
    private readonly global::System.Collections.Generic.List<G2C.StartGameReply.Item> _used_item_list = new global::System.Collections.Generic.List<G2C.StartGameReply.Item>();
    [global::ProtoBuf.ProtoMember(4, Name=@"used_item_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<G2C.StartGameReply.Item> used_item_list
    {
      get { return _used_item_list; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item")]
  public partial class Item : global::ProtoBuf.IExtensible
  {
    public Item() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bool _on;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"on", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool on
    {
      get { return _on; }
      set { _on = value; }
    }
    private int _rest;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rest", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rest
    {
      get { return _rest; }
      set { _rest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccountInfo")]
  public partial class AccountInfo : global::ProtoBuf.IExtensible
  {
    public AccountInfo() {}
    

    private ulong _id = (ulong)76741253;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)76741253)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _lv;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private int _exp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _cash;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"cash", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cash
    {
      get { return _cash; }
      set { _cash = value; }
    }
    private int _energy;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int energy
    {
      get { return _energy; }
      set { _energy = value; }
    }
    private long _last_charged_time;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"last_charged_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long last_charged_time
    {
      get { return _last_charged_time; }
      set { _last_charged_time = value; }
    }
    private int _selected_character;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"selected_character", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int selected_character
    {
      get { return _selected_character; }
      set { _selected_character = value; }
    }
    private int _item_1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"item_1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item_1
    {
      get { return _item_1; }
      set { _item_1 = value; }
    }
    private int _item_2;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"item_2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item_2
    {
      get { return _item_2; }
      set { _item_2 = value; }
    }
    private int _item_3;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"item_3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item_3
    {
      get { return _item_3; }
      set { _item_3 = value; }
    }
    private int _item_4;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"item_4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item_4
    {
      get { return _item_4; }
      set { _item_4 = value; }
    }
    private int _item_5;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"item_5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item_5
    {
      get { return _item_5; }
      set { _item_5 = value; }
    }
    private int _random;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"random", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int random
    {
      get { return _random; }
      set { _random = value; }
    }
    private int _mileage;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"mileage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mileage
    {
      get { return _mileage; }
      set { _mileage = value; }
    }
    private int _draw;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int draw
    {
      get { return _draw; }
      set { _draw = value; }
    }
    private int _highest_score;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"highest_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int highest_score
    {
      get { return _highest_score; }
      set { _highest_score = value; }
    }
    private readonly global::System.Collections.Generic.List<G2C.AccountInfo.CharacterInfo> _characters = new global::System.Collections.Generic.List<G2C.AccountInfo.CharacterInfo>();
    [global::ProtoBuf.ProtoMember(18, Name=@"characters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<G2C.AccountInfo.CharacterInfo> characters
    {
      get { return _characters; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterInfo")]
  public partial class CharacterInfo : global::ProtoBuf.IExtensible
  {
    public CharacterInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogoutReply")]
  public partial class LogoutReply : global::ProtoBuf.IExtensible
  {
    public LogoutReply() {}
    

    private ulong _id = (ulong)1481109953;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)1481109953)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChargeInfo")]
  public partial class ChargeInfo : global::ProtoBuf.IExtensible
  {
    public ChargeInfo() {}
    

    private ulong _id = (ulong)149157351;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)149157351)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _energy;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int energy
    {
      get { return _energy; }
      set { _energy = value; }
    }
    private long _last_charged_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"last_charged_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long last_charged_time
    {
      get { return _last_charged_time; }
      set { _last_charged_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankInfo")]
  public partial class RankInfo : global::ProtoBuf.IExtensible
  {
    public RankInfo() {}
    

    private ulong _id = (ulong)9108294;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)9108294)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private long _overall_ranking;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"overall_ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long overall_ranking
    {
      get { return _overall_ranking; }
      set { _overall_ranking = value; }
    }
    private readonly global::System.Collections.Generic.List<G2C.RankInfo.FriendRankInfo> _ranking_list = new global::System.Collections.Generic.List<G2C.RankInfo.FriendRankInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ranking_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<G2C.RankInfo.FriendRankInfo> ranking_list
    {
      get { return _ranking_list; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendRankInfo")]
  public partial class FriendRankInfo : global::ProtoBuf.IExtensible
  {
    public FriendRankInfo() {}
    
    private string _k_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string k_id
    {
      get { return _k_id; }
      set { _k_id = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private bool _energy_sended;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"energy_sended", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool energy_sended
    {
      get { return _energy_sended; }
      set { _energy_sended = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameResult")]
  public partial class GameResult : global::ProtoBuf.IExtensible
  {
    public GameResult() {}
    

    private ulong _id = (ulong)130595;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)130595)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _bonus_score;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bonus_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bonus_score
    {
      get { return _bonus_score; }
      set { _bonus_score = value; }
    }
    private int _total_score;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"total_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int total_score
    {
      get { return _total_score; }
      set { _total_score = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _bonus_coin;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"bonus_coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bonus_coin
    {
      get { return _bonus_coin; }
      set { _bonus_coin = value; }
    }
    private int _total_coin;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"total_coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int total_coin
    {
      get { return _total_coin; }
      set { _total_coin = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _exp;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _bonus_exp;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"bonus_exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bonus_exp
    {
      get { return _bonus_exp; }
      set { _bonus_exp = value; }
    }
    private int _total_exp;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"total_exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int total_exp
    {
      get { return _total_exp; }
      set { _total_exp = value; }
    }
    private int _mileage;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"mileage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mileage
    {
      get { return _mileage; }
      set { _mileage = value; }
    }
    private int _total_mileage;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"total_mileage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int total_mileage
    {
      get { return _total_mileage; }
      set { _total_mileage = value; }
    }
    private int _draw;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int draw
    {
      get { return _draw; }
      set { _draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyItemReply")]
  public partial class BuyItemReply : global::ProtoBuf.IExtensible
  {
    public BuyItemReply() {}
    

    private ulong _id = (ulong)3144697;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)3144697)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _item;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item
    {
      get { return _item; }
      set { _item = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyOrUpgradeCharacterReply")]
  public partial class BuyOrUpgradeCharacterReply : global::ProtoBuf.IExtensible
  {
    public BuyOrUpgradeCharacterReply() {}
    

    private ulong _id = (ulong)6158802;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)6158802)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _character;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"character", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int character
    {
      get { return _character; }
      set { _character = value; }
    }
    private int _lv;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _cash;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"cash", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cash
    {
      get { return _cash; }
      set { _cash = value; }
    }
    private int _mileage;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"mileage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mileage
    {
      get { return _mileage; }
      set { _mileage = value; }
    }
    private int _draw;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int draw
    {
      get { return _draw; }
      set { _draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendEnergyReply")]
  public partial class SendEnergyReply : global::ProtoBuf.IExtensible
  {
    public SendEnergyReply() {}
    

    private ulong _id = (ulong)2161529;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)2161529)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _mileage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mileage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mileage
    {
      get { return _mileage; }
      set { _mileage = value; }
    }
    private int _draw;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int draw
    {
      get { return _draw; }
      set { _draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestBatonReply")]
  public partial class RequestBatonReply : global::ProtoBuf.IExtensible
  {
    public RequestBatonReply() {}
    

    private ulong _id = (ulong)5174726;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)5174726)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _cash;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cash", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cash
    {
      get { return _cash; }
      set { _cash = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcceptEnergyReply")]
  public partial class AcceptEnergyReply : global::ProtoBuf.IExtensible
  {
    public AcceptEnergyReply() {}
    

    private ulong _id = (ulong)5176545;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)5176545)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _energy;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int energy
    {
      get { return _energy; }
      set { _energy = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InviteFriendReply")]
  public partial class InviteFriendReply : global::ProtoBuf.IExtensible
  {
    public InviteFriendReply() {}
    

    private ulong _id = (ulong)6223418;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)6223418)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _invite_count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"invite_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int invite_count
    {
      get { return _invite_count; }
      set { _invite_count = value; }
    }
    private int _mileage;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mileage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mileage
    {
      get { return _mileage; }
      set { _mileage = value; }
    }
    private int _draw;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int draw
    {
      get { return _draw; }
      set { _draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadRewardReply")]
  public partial class LoadRewardReply : global::ProtoBuf.IExtensible
  {
    public LoadRewardReply() {}
    

    private ulong _id = (ulong)193285;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)193285)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private G2C.LoadRewardReply.Reward _reward;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public G2C.LoadRewardReply.Reward reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Reward")]
    public enum Reward
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVITE_10_REWARD", Value=1)]
      INVITE_10_REWARD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVITE_15_REWARD", Value=2)]
      INVITE_15_REWARD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVITE_30_REWARD", Value=3)]
      INVITE_30_REWARD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX", Value=4)]
      MAX = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyCostumeReply")]
  public partial class BuyCostumeReply : global::ProtoBuf.IExtensible
  {
    public BuyCostumeReply() {}
    

    private ulong _id = (ulong)9239350;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)9239350)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _costume_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"costume_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int costume_id
    {
      get { return _costume_id; }
      set { _costume_id = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _cash;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"cash", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cash
    {
      get { return _cash; }
      set { _cash = value; }
    }
    private int _mileage;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mileage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mileage
    {
      get { return _mileage; }
      set { _mileage = value; }
    }
    private int _draw;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"draw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int draw
    {
      get { return _draw; }
      set { _draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WearCostumeReply")]
  public partial class WearCostumeReply : global::ProtoBuf.IExtensible
  {
    public WearCostumeReply() {}
    

    private ulong _id = (ulong)3208394;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)3208394)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _costume_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"costume_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int costume_id
    {
      get { return _costume_id; }
      set { _costume_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DrawFirstReply")]
  public partial class DrawFirstReply : global::ProtoBuf.IExtensible
  {
    public DrawFirstReply() {}
    

    private ulong _id = (ulong)4258269;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)4258269)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private G2C.DrawFirstReply.Draw _pick;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public G2C.DrawFirstReply.Draw pick
    {
      get { return _pick; }
      set { _pick = value; }
    }
    private readonly global::System.Collections.Generic.List<G2C.DrawFirstReply.Draw> _draw_list = new global::System.Collections.Generic.List<G2C.DrawFirstReply.Draw>();
    [global::ProtoBuf.ProtoMember(3, Name=@"draw_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<G2C.DrawFirstReply.Draw> draw_list
    {
      get { return _draw_list; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Draw")]
  public partial class Draw : global::ProtoBuf.IExtensible
  {
    public Draw() {}
    
    private bool _is_ghost;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"is_ghost", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_ghost
    {
      get { return _is_ghost; }
      set { _is_ghost = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DrawSecondReply")]
  public partial class DrawSecondReply : global::ProtoBuf.IExtensible
  {
    public DrawSecondReply() {}
    

    private ulong _id = (ulong)5240700;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)5240700)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private G2C.DrawSecondReply.Draw _pick;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public G2C.DrawSecondReply.Draw pick
    {
      get { return _pick; }
      set { _pick = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Draw")]
  public partial class Draw : global::ProtoBuf.IExtensible
  {
    public Draw() {}
    
    private bool _is_ghost;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"is_ghost", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_ghost
    {
      get { return _is_ghost; }
      set { _is_ghost = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipGhostReply")]
  public partial class EquipGhostReply : global::ProtoBuf.IExtensible
  {
    public EquipGhostReply() {}
    

    private ulong _id = (ulong)1243519;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)1243519)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _ghost_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ghost_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ghost_id
    {
      get { return _ghost_id; }
      set { _ghost_id = value; }
    }
    private int _house_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"house_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int house_id
    {
      get { return _house_id; }
      set { _house_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnequipGhostReply")]
  public partial class UnequipGhostReply : global::ProtoBuf.IExtensible
  {
    public UnequipGhostReply() {}
    

    private ulong _id = (ulong)7273008;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)7273008)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _house_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"house_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int house_id
    {
      get { return _house_id; }
      set { _house_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PurchaseHouseReply")]
  public partial class PurchaseHouseReply : global::ProtoBuf.IExtensible
  {
    public PurchaseHouseReply() {}
    

    private ulong _id = (ulong)5307594;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)5307594)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _house_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"house_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int house_id
    {
      get { return _house_id; }
      set { _house_id = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _cash;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"cash", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cash
    {
      get { return _cash; }
      set { _cash = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestEvolutionReply")]
  public partial class RequestEvolutionReply : global::ProtoBuf.IExtensible
  {
    public RequestEvolutionReply() {}
    

    private ulong _id = (ulong)6288932;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)6288932)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcceptEvolutionReply")]
  public partial class AcceptEvolutionReply : global::ProtoBuf.IExtensible
  {
    public AcceptEvolutionReply() {}
    

    private ulong _id = (ulong)7274368;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)7274368)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EvolutionProgress")]
  public partial class EvolutionProgress : global::ProtoBuf.IExtensible
  {
    public EvolutionProgress() {}
    

    private ulong _id = (ulong)326084;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)326084)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<G2C.EvolutionProgress.Progress> _progress = new global::System.Collections.Generic.List<G2C.EvolutionProgress.Progress>();
    [global::ProtoBuf.ProtoMember(2, Name=@"progress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<G2C.EvolutionProgress.Progress> progress
    {
      get { return _progress; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Progress")]
  public partial class Progress : global::ProtoBuf.IExtensible
  {
    public Progress() {}
    
    private int _character_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"character_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int character_id
    {
      get { return _character_id; }
      set { _character_id = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _accepted_k_id = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"accepted_k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> accepted_k_id
    {
      get { return _accepted_k_id; }
    }
  
    private int _lv;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Postbox")]
  public partial class Postbox : global::ProtoBuf.IExtensible
  {
    public Postbox() {}
    

    private ulong _id = (ulong)10351731;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)10351731)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<G2C.Postbox.Energy> _energy = new global::System.Collections.Generic.List<G2C.Postbox.Energy>();
    [global::ProtoBuf.ProtoMember(2, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<G2C.Postbox.Energy> energy
    {
      get { return _energy; }
    }
  
    private readonly global::System.Collections.Generic.List<G2C.Postbox.Evolution> _evolution = new global::System.Collections.Generic.List<G2C.Postbox.Evolution>();
    [global::ProtoBuf.ProtoMember(3, Name=@"evolution", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<G2C.Postbox.Evolution> evolution
    {
      get { return _evolution; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Energy")]
  public partial class Energy : global::ProtoBuf.IExtensible
  {
    public Energy() {}
    
    private string _sender_k_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sender_k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sender_k_id
    {
      get { return _sender_k_id; }
      set { _sender_k_id = value; }
    }
    private int _amount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private long _sended_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sended_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sended_time
    {
      get { return _sended_time; }
      set { _sended_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Evolution")]
  public partial class Evolution : global::ProtoBuf.IExtensible
  {
    public Evolution() {}
    
    private string _sender_k_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sender_k_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sender_k_id
    {
      get { return _sender_k_id; }
      set { _sender_k_id = value; }
    }
    private int _character_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"character_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int character_id
    {
      get { return _character_id; }
      set { _character_id = value; }
    }
    private long _sended_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sended_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sended_time
    {
      get { return _sended_time; }
      set { _sended_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}