USE sea_log;

DROP TABLE IF EXISTS sea_pay_item;

CREATE TABLE sea_log.sea_pay_item(
	id INT NOT NULL AUTO_INCREMENT,
	k_id VARCHAR(40) NOT NULL,
	w_date DATE NOT NULL,
	w_time TIME NOT NULL,
	paid_item SMALLINT NOT NULL,
	rest_coin MEDIUMINT NOT NULL,
	PRIMARY KEY (id, w_date)
)ENGINE=MyISAM
PARTITION BY RANGE COLUMNS (w_date) (
	PARTITION p201308 VALUES LESS THAN ('2013-09-01'),
	PARTITION p201309 VALUES LESS THAN ('2013-10-01'),
	PARTITION p201310 VALUES LESS THAN ('2013-11-01'),
	PARTITION p201311 VALUES LESS THAN ('2013-12-01'),
	PARTITION p201312 VALUES LESS THAN ('2014-01-01'),
	PARTITION pMAX VALUES LESS THAN (MAXVALUE)
);

DELIMITER $$

DROP PROCEDURE IF EXISTS sea_AddLogPayItem $$
CREATE PROCEDURE sea_AddLogPayItem(IN p_k_id VARCHAR (40) CHARACTER SET utf8, IN p_paid_item SMALLINT, IN p_rest_coin MEDIUMINT)
	BEGIN
		INSERT sea_pay_item(k_id, w_date, w_time, paid_item, rest_coin)
		VALUES (p_k_id, CURDATE(), CURTIME(), p_paid_item, p_rest_coin);

		SELECT LAST_INSERT_ID() AS res;
	END
$$

DELIMITER ;
