USE sea_log;

DROP TABLE IF EXISTS sea_pay_money;

CREATE TABLE sea_log.sea_pay_money(
	id INT NOT NULL AUTO_INCREMENT,
	k_id VARCHAR(40) NOT NULL,
	w_date DATE NOT NULL,
	w_time TIME NOT NULL,
	paid_money SMALLINT NOT NULL,
	rest_money MEDIUMINT NOT NULL,
	PRIMARY KEY (id, w_date)
)ENGINE=MyISAM
PARTITION BY RANGE COLUMNS (w_date) (
	PARTITION p201308 VALUES LESS THAN ('2013-09-01'),
	PARTITION p201309 VALUES LESS THAN ('2013-10-01'),
	PARTITION p201310 VALUES LESS THAN ('2013-11-01'),
	PARTITION p201311 VALUES LESS THAN ('2013-12-01'),
	PARTITION p201312 VALUES LESS THAN ('2014-01-01'),
	PARTITION pMAX VALUES LESS THAN (MAXVALUE)
);

DELIMITER $$

DROP PROCEDURE IF EXISTS sea_AddLogPayMoney $$
CREATE PROCEDURE sea_AddLogPayMoney(IN p_k_id VARCHAR (40) CHARACTER SET utf8, IN p_paid_money SMALLINT, IN p_rest_money MEDIUMINT)
	BEGIN
		INSERT sea_pay_money(k_id, w_date, w_time, paid_character, rest_money)
		VALUES (p_k_id, CURDATE(), CURTIME(), p_paid_money, p_rest_money);

		SELECT LAST_INSERT_ID() AS res;
	END
$$

DELIMITER ;
