USE sea_log;

DROP TABLE IF EXISTS sea_unique_visitor;

CREATE TABLE sea_log.sea_unique_visitor(
	id INT NOT NULL AUTO_INCREMENT,
	w_date DATE NOT NULL,
	uv INT UNSIGNED NOT NULL,
	PRIMARY KEY (id, w_date)
)ENGINE=MyISAM
PARTITION BY RANGE COLUMNS (w_date) (
	PARTITION p201308 VALUES LESS THAN ('2013-09-01'),
	PARTITION p201309 VALUES LESS THAN ('2013-10-01'),
	PARTITION p201310 VALUES LESS THAN ('2013-11-01'),
	PARTITION p201311 VALUES LESS THAN ('2013-12-01'),
	PARTITION p201312 VALUES LESS THAN ('2014-01-01'),
	PARTITION pMAX VALUES LESS THAN (MAXVALUE)
);

DELIMITER $$

DROP PROCEDURE IF EXISTS sea_AddUniqueVisitor $$
CREATE PROCEDURE sea_AddUniqueVisitor(IN p_uv INT UNSIGNED)
	BEGIN
		INSERT sea_unique_visitor(w_date, uv)
		VALUES (subdate(CURDATE(), 1), p_uv);

		SELECT LAST_INSERT_ID() AS res;
	END
$$

DELIMITER ;
