var build = require('./gameProtoBuild');

var msgs = [
	{'msg': 'VersionInfo', 'instance': new build.VersionInfo(), 'build': build.VersionInfo}, 
	{'msg': 'RegisterAccount', 'instance': new build.RegisterAccount(), 'build': build.RegisterAccount}, 
	{'msg': 'UnregisterAccount', 'instance': new build.UnregisterAccount(), 'build': build.UnregisterAccount}, 
	{'msg': 'Login', 'instance': new build.Login(), 'build': build.Login}, 
	{'msg': 'Logout', 'instance': new build.Logout(), 'build': build.Logout}, 
	{'msg': 'CheckInCharge', 'instance': new build.CheckInCharge(), 'build': build.CheckInCharge}, 
	{'msg': 'SelectCharacter', 'instance': new build.SelectCharacter(), 'build': build.SelectCharacter}, 
	{'msg': 'SelectAssistant', 'instance': new build.SelectAssistant(), 'build': build.SelectAssistant}, 
	{'msg': 'StartGame', 'instance': new build.StartGame(), 'build': build.StartGame}, 
	{'msg': 'EndGame', 'instance': new build.EndGame(), 'build': build.EndGame}, 
	{'msg': 'LoadRankInfo', 'instance': new build.LoadRankInfo(), 'build': build.LoadRankInfo}, 
	{'msg': 'LoadPostedHoney', 'instance': new build.LoadPostedHoney(), 'build': build.LoadPostedHoney}, 
	{'msg': 'LoadPostedBaton', 'instance': new build.LoadPostedBaton(), 'build': build.LoadPostedBaton}, 
	{'msg': 'LoadPostedBatonResult', 'instance': new build.LoadPostedBatonResult(), 'build': build.LoadPostedBatonResult}, 
	{'msg': 'RequestPointReward', 'instance': new build.RequestPointReward(), 'build': build.RequestPointReward}, 
	{'msg': 'BuyItem', 'instance': new build.BuyItem(), 'build': build.BuyItem}, 
	{'msg': 'BuyCharacter', 'instance': new build.BuyCharacter(), 'build': build.BuyCharacter}, 
	{'msg': 'BuyAssistant', 'instance': new build.BuyAssistant(), 'build': build.BuyAssistant}, 
	{'msg': 'SendHoney', 'instance': new build.SendHoney(), 'build': build.SendHoney}, 
	{'msg': 'AcceptHoney', 'instance': new build.AcceptHoney(), 'build': build.AcceptHoney}, 
	{'msg': 'RequestBaton', 'instance': new build.RequestBaton(), 'build': build.RequestBaton}, 
	{'msg': 'AcceptBaton', 'instance': new build.AcceptBaton(), 'build': build.AcceptBaton}, 
	{'msg': 'EndBaton', 'instance': new build.EndBaton(), 'build': build.EndBaton}, 
	{'msg': 'AcceptBatonResult', 'instance': new build.AcceptBatonResult(), 'build': build.AcceptBatonResult}, 
	{'msg': 'UpgradeHoneyScore', 'instance': new build.UpgradeHoneyScore(), 'build': build.UpgradeHoneyScore}, 
	{'msg': 'UpgradeHoneyTime', 'instance': new build.UpgradeHoneyTime(), 'build': build.UpgradeHoneyTime}, 
	{'msg': 'UpgradeCooldown', 'instance': new build.UpgradeCooldown(), 'build': build.UpgradeCooldown}, 
	{'msg': 'UpgradeMaxAttack', 'instance': new build.UpgradeMaxAttack(), 'build': build.UpgradeMaxAttack}, 
	{'msg': 'UpgradePet', 'instance': new build.UpgradePet(), 'build': build.UpgradePet}, 
	{'msg': 'SystemMessage', 'instance': new build.SystemMessage(), 'build': build.SystemMessage}, 
	{'msg': 'VersionInfoReply', 'instance': new build.VersionInfoReply(), 'build': build.VersionInfoReply}, 
	{'msg': 'RegisterAccountReply', 'instance': new build.RegisterAccountReply(), 'build': build.RegisterAccountReply}, 
	{'msg': 'SelectCharacterReply', 'instance': new build.SelectCharacterReply(), 'build': build.SelectCharacterReply}, 
	{'msg': 'SelectAssistantReply', 'instance': new build.SelectAssistantReply(), 'build': build.SelectAssistantReply}, 
	{'msg': 'StartGameReply', 'instance': new build.StartGameReply(), 'build': build.StartGameReply}, 
	{'msg': 'AccountInfo', 'instance': new build.AccountInfo(), 'build': build.AccountInfo}, 
	{'msg': 'LogoutReply', 'instance': new build.LogoutReply(), 'build': build.LogoutReply}, 
	{'msg': 'ChargeInfo', 'instance': new build.ChargeInfo(), 'build': build.ChargeInfo}, 
	{'msg': 'RankInfo', 'instance': new build.RankInfo(), 'build': build.RankInfo}, 
	{'msg': 'PostedHoney', 'instance': new build.PostedHoney(), 'build': build.PostedHoney}, 
	{'msg': 'PostedBaton', 'instance': new build.PostedBaton(), 'build': build.PostedBaton}, 
	{'msg': 'PostedBatonResult', 'instance': new build.PostedBatonResult(), 'build': build.PostedBatonResult}, 
	{'msg': 'GameResult', 'instance': new build.GameResult(), 'build': build.GameResult}, 
	{'msg': 'BuyItemReply', 'instance': new build.BuyItemReply(), 'build': build.BuyItemReply}, 
	{'msg': 'BuyCharacterReply', 'instance': new build.BuyCharacterReply(), 'build': build.BuyCharacterReply}, 
	{'msg': 'BuyAssistantReply', 'instance': new build.BuyAssistantReply(), 'build': build.BuyAssistantReply}, 
	{'msg': 'SendHoneyReply', 'instance': new build.SendHoneyReply(), 'build': build.SendHoneyReply}, 
	{'msg': 'RequestBatonReply', 'instance': new build.RequestBatonReply(), 'build': build.RequestBatonReply}, 
	{'msg': 'AcceptHoneyReply', 'instance': new build.AcceptHoneyReply(), 'build': build.AcceptHoneyReply}, 
	{'msg': 'AcceptBatonReply', 'instance': new build.AcceptBatonReply(), 'build': build.AcceptBatonReply}, 
	{'msg': 'BatonResult', 'instance': new build.BatonResult(), 'build': build.BatonResult}, 
	{'msg': 'AcceptBatonResultReply', 'instance': new build.AcceptBatonResultReply(), 'build': build.AcceptBatonResultReply}, 
	{'msg': 'UpgradeReply', 'instance': new build.UpgradeReply(), 'build': build.UpgradeReply}, 
];

exports.msgs = msgs;